// clang-format off
// Generated by utils/generate_win32_nt_tables.py; do not edit.
// win32 GetLastError() error code -> std::errc; case 0 is ERROR_SUCCESS.
// Requires <cerrno> and ::std::errc.

	case 0u:
		return ::std::errc{};

#ifdef ENOSYS
	case 0x1u:
		return ::std::errc::function_not_supported;
#endif
#ifdef ENOENT
	case 0x2u:
		return ::std::errc::no_such_file_or_directory;
#endif
#ifdef ENOENT
	case 0x3u:
		return ::std::errc::no_such_file_or_directory;
#endif
#ifdef EMFILE
	case 0x4u:
		return ::std::errc::too_many_files_open;
#endif
#ifdef EACCES
	case 0x5u:
		return ::std::errc::permission_denied;
#endif
#ifdef EINVAL
	case 0x6u:
		return ::std::errc::invalid_argument;
#endif
#ifdef ENOMEM
	case 0x8u:
		return ::std::errc::not_enough_memory;
#endif
#ifdef EACCES
	case 0xcu:
		return ::std::errc::permission_denied;
#endif
#ifdef ENOMEM
	case 0xeu:
		return ::std::errc::not_enough_memory;
#endif
#ifdef ENODEV
	case 0xfu:
		return ::std::errc::no_such_device;
#endif
#ifdef EACCES
	case 0x10u:
		return ::std::errc::permission_denied;
#endif
#ifdef EXDEV
	case 0x11u:
		return ::std::errc::cross_device_link;
#endif
#ifdef EACCES
	case 0x13u:
		return ::std::errc::permission_denied;
#endif
#ifdef ENODEV
	case 0x14u:
		return ::std::errc::no_such_device;
#endif
#ifdef EAGAIN
	case 0x15u:
		return ::std::errc::resource_unavailable_try_again;
#endif
#ifdef EIO
	case 0x19u:
		return ::std::errc::io_error;
#endif
#ifdef EIO
	case 0x1du:
		return ::std::errc::io_error;
#endif
#ifdef EIO
	case 0x1eu:
		return ::std::errc::io_error;
#endif
#ifdef EACCES
	case 0x20u:
		return ::std::errc::permission_denied;
#endif
#ifdef ENOLCK
	case 0x21u:
		return ::std::errc::no_lock_available;
#endif
#ifdef ENOSPC
	case 0x27u:
		return ::std::errc::no_space_on_device;
#endif
#ifdef ENODEV
	case 0x37u:
		return ::std::errc::no_such_device;
#endif
#ifdef EEXIST
	case 0x50u:
		return ::std::errc::file_exists;
#endif
#ifdef EACCES
	case 0x52u:
		return ::std::errc::permission_denied;
#endif
#ifdef EINVAL
	case 0x57u:
		return ::std::errc::invalid_argument;
#endif
#ifdef EIO
	case 0x6eu:
		return ::std::errc::io_error;
#endif
#ifdef ENAMETOOLONG
	case 0x6fu:
		return ::std::errc::filename_too_long;
#endif
#ifdef ENOSPC
	case 0x70u:
		return ::std::errc::no_space_on_device;
#endif
#ifdef EINVAL
	case 0x7bu:
		return ::std::errc::invalid_argument;
#endif
#ifdef EINVAL
	case 0x83u:
		return ::std::errc::invalid_argument;
#endif
#ifdef EBUSY
	case 0x8eu:
		return ::std::errc::device_or_resource_busy;
#endif
#ifdef ENOTEMPTY
	case 0x91u:
		return ::std::errc::directory_not_empty;
#endif
#ifdef EBUSY
	case 0xaau:
		return ::std::errc::device_or_resource_busy;
#endif
#ifdef EEXIST
	case 0xb7u:
		return ::std::errc::file_exists;
#endif
#ifdef ENOLCK
	case 0xd4u:
		return ::std::errc::no_lock_available;
#endif
#ifdef EINVAL
	case 0x10bu:
		return ::std::errc::invalid_argument;
#endif
#ifdef ECANCELED
	case 0x3e3u:
		return ::std::errc::operation_canceled;
#endif
#ifdef EACCES
	case 0x3e6u:
		return ::std::errc::permission_denied;
#endif
#ifdef EIO
	case 0x3f3u:
		return ::std::errc::io_error;
#endif
#ifdef EIO
	case 0x3f4u:
		return ::std::errc::io_error;
#endif
#ifdef EIO
	case 0x3f5u:
		return ::std::errc::io_error;
#endif
#ifdef EAGAIN
	case 0x4d5u:
		return ::std::errc::resource_unavailable_try_again;
#endif
#ifdef EBUSY
	case 0x961u:
		return ::std::errc::device_or_resource_busy;
#endif
#ifdef EBUSY
	case 0x964u:
		return ::std::errc::device_or_resource_busy;
#endif
#ifdef EINTR
	case 0x2714u:
		return ::std::errc::interrupted;
#endif
#ifdef EBADF
	case 0x2719u:
		return ::std::errc::bad_file_descriptor;
#endif
#ifdef EACCES
	case 0x271du:
		return ::std::errc::permission_denied;
#endif
#ifdef EFAULT
	case 0x271eu:
		return ::std::errc::bad_address;
#endif
#ifdef EINVAL
	case 0x2726u:
		return ::std::errc::invalid_argument;
#endif
#ifdef EMFILE
	case 0x2728u:
		return ::std::errc::too_many_files_open;
#endif
#ifdef EWOULDBLOCK
	case 0x2733u:
		return ::std::errc::operation_would_block;
#endif
#ifdef EINPROGRESS
	case 0x2734u:
		return ::std::errc::operation_in_progress;
#endif
#ifdef EALREADY
	case 0x2735u:
		return ::std::errc::connection_already_in_progress;
#endif
#ifdef ENOTSOCK
	case 0x2736u:
		return ::std::errc::not_a_socket;
#endif
#ifdef EDESTADDRREQ
	case 0x2737u:
		return ::std::errc::destination_address_required;
#endif
#ifdef EMSGSIZE
	case 0x2738u:
		return ::std::errc::message_size;
#endif
#ifdef EPROTOTYPE
	case 0x2739u:
		return ::std::errc::wrong_protocol_type;
#endif
#ifdef ENOPROTOOPT
	case 0x273au:
		return ::std::errc::no_protocol_option;
#endif
#ifdef EPROTONOSUPPORT
	case 0x273bu:
		return ::std::errc::protocol_not_supported;
#endif
#ifdef EOPNOTSUPP
	case 0x273du:
		return ::std::errc::operation_not_supported;
#endif
#ifdef EAFNOSUPPORT
	case 0x273fu:
		return ::std::errc::address_family_not_supported;
#endif
#ifdef EADDRINUSE
	case 0x2740u:
		return ::std::errc::address_in_use;
#endif
#ifdef EADDRNOTAVAIL
	case 0x2741u:
		return ::std::errc::address_not_available;
#endif
#ifdef ENETDOWN
	case 0x2742u:
		return ::std::errc::network_down;
#endif
#ifdef ENETUNREACH
	case 0x2743u:
		return ::std::errc::network_unreachable;
#endif
#ifdef ENETRESET
	case 0x2744u:
		return ::std::errc::network_reset;
#endif
#ifdef ECONNABORTED
	case 0x2745u:
		return ::std::errc::connection_aborted;
#endif
#ifdef ECONNRESET
	case 0x2746u:
		return ::std::errc::connection_reset;
#endif
#ifdef ENOBUFS
	case 0x2747u:
		return ::std::errc::no_buffer_space;
#endif
#ifdef EISCONN
	case 0x2748u:
		return ::std::errc::already_connected;
#endif
#ifdef ENOTCONN
	case 0x2749u:
		return ::std::errc::not_connected;
#endif
#ifdef ETIMEDOUT
	case 0x274cu:
		return ::std::errc::timed_out;
#endif
#ifdef ECONNREFUSED
	case 0x274du:
		return ::std::errc::connection_refused;
#endif
#ifdef ENAMETOOLONG
	case 0x274fu:
		return ::std::errc::filename_too_long;
#endif
#ifdef EHOSTUNREACH
	case 0x2751u:
		return ::std::errc::host_unreachable;
#endif

	default:
		return ::std::errc::io_error;
// clang-format on
