ERRORS = [
    ("0", "Success"),

    ("EPERM", "Not owner",
        "defined(EPERM) && (!defined(EACCES) || (EPERM != EACCES))"),

    ("ENOENT", "No such file or directory"),

    ("ESRCH", "No such process"),
    ("EINTR", "Interrupted system call"),
    ("EIO", "I/O error"),

    ("ENXIO", "No such device or address",
        "defined(ENXIO) && (!defined(ENODEV) || (ENXIO != ENODEV))"),

    ("E2BIG", "Arg list too long"),
    ("ENOEXEC", "Exec format error"),
    ("EALREADY", "Socket already connected"),
    ("EBADF", "Bad file number"),
    ("ECHILD", "No children"),
    ("EDESTADDRREQ", "Destination address required"),
    ("EAGAIN", "No more processes"),
    ("ENOMEM", "Not enough space"),
    ("EACCES", "Permission denied"),
    ("EFAULT", "Bad address"),
    ("ENOTBLK", "Block device required"),
    ("EBUSY", "Device or resource busy"),
    ("EEXIST", "File exists"),
    ("EXDEV", "Cross-device link"),
    ("ENODEV", "No such device"),
    ("ENOTDIR", "Not a directory"),
    ("EHOSTDOWN", "Host is down"),
    ("EINPROGRESS", "Connection already in progress"),
    ("EISDIR", "Is a directory"),
    ("EINVAL", "Invalid argument"),
    ("ENETDOWN", "Network interface is not configured"),
    ("ENETRESET", "Connection aborted by network"),
    ("ENFILE", "Too many open files in system"),
    ("EMFILE", "File descriptor value too large"),
    ("ENOTTY", "Not a character device"),
    ("ETXTBSY", "Text file busy"),
    ("EFBIG", "File too large"),
    ("EHOSTUNREACH", "Host is unreachable"),
    ("ENOSPC", "No space left on device"),
    ("ENOTSUP", "Not supported"),
    ("ESPIPE", "Illegal seek"),
    ("EROFS", "Read-only file system"),
    ("EMLINK", "Too many links"),
    ("EPIPE", "Broken pipe"),
    ("EDOM", "Mathematics argument out of domain of function"),
    ("ERANGE", "Result too large"),
    ("ENOMSG", "No message of desired type"),
    ("EIDRM", "Identifier removed"),
    ("EILSEQ", "Illegal byte sequence"),
    ("EDEADLK", "Deadlock"),
    ("ENETUNREACH", "Network is unreachable"),
    ("ENOLCK", "No lock"),
    ("ENOSTR", "Not a stream"),
    ("ETIME", "Stream ioctl timeout"),
    ("ENOSR", "No stream resources"),
    ("ENONET", "Machine is not on the network"),
    ("ENOPKG", "No package"),
    ("EREMOTE", "Resource is remote"),
    ("ENOLINK", "Virtual circuit is gone"),
    ("EADV", "Advertise error"),
    ("ESRMNT", "Srmount error"),
    ("ECOMM", "Communication error"),
    ("EPROTO", "Protocol error"),
    ("EPROTONOSUPPORT", "Unknown protocol"),
    ("EMULTIHOP", "Multihop attempted"),
    ("EBADMSG", "Bad message"),
    ("ELIBACC", "Cannot access a needed shared library"),
    ("ELIBBAD", "Accessing a corrupted shared library"),
    ("ELIBSCN", ".lib section in a.out corrupted"),
    ("ELIBMAX", "Attempting to link in more shared libraries than system limit"),
    ("ELIBEXEC", "Cannot exec a shared library directly"),
    ("ENOSYS", "Function not implemented"),
    ("ENMFILE", "No more files"),
    ("ENOTEMPTY", "Directory not empty"),
    ("ENAMETOOLONG", "File or path name too long"),
    ("ELOOP", "Too many symbolic links"),
    ("ENOBUFS", "No buffer space available"),
    ("ENODATA", "No data"),
    ("EAFNOSUPPORT", "Address family not supported by protocol family"),
    ("EPROTOTYPE", "Protocol wrong type for socket"),
    ("ENOTSOCK", "Socket operation on non-socket"),
    ("ENOPROTOOPT", "Protocol not available"),
    ("ESHUTDOWN", "Can't send after socket shutdown"),
    ("ECONNREFUSED", "Connection refused"),
    ("ECONNRESET", "Connection reset by peer"),
    ("EADDRINUSE", "Address already in use"),
    ("EADDRNOTAVAIL", "Address not available"),
    ("ECONNABORTED", "Software caused connection abort"),

    ("EWOULDBLOCK", "Operation would block",
        "defined(EWOULDBLOCK) && (!defined(EAGAIN) || (EWOULDBLOCK != EAGAIN))"),

    ("ENOTCONN", "Socket is not connected"),
    ("ESOCKTNOSUPPORT", "Socket type not supported"),
    ("EISCONN", "Socket is already connected"),
    ("ECANCELED", "Operation canceled"),
    ("ENOTRECOVERABLE", "State not recoverable"),
    ("EOWNERDEAD", "Previous owner died"),
    ("ESTRPIPE", "Streams pipe error"),

    ("EOPNOTSUPP", "Operation not supported on socket",
        "defined(EOPNOTSUPP) && (!defined(ENOTSUP) || (ENOTSUP != EOPNOTSUPP))"),

    ("EOVERFLOW", "Value too large for defined data type"),
    ("EMSGSIZE", "Message too long"),
    ("ETIMEDOUT", "Connection timed out"),

    ("UNKNOWN", "Unknown")
]


